resources:
  - url: http://127.0.0.1:5000/rpi-monitor-card.js
    type: module
views:
  - cards:
      - type: custom:rpi-monitor-card
        name: RPi Monitor Card Development
        entity: sun.sun
        test_gui: true
